import Image from "next/image";

export default function Gallery() {
    return (
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            <div>
                <Image
                    src="/husko1_modi.png"
                    alt=""
                    height={600}
                    width={600}
                    quality={100}
                    priority
                />
            </div>
            <div>
                <Image
                    src="/husko2.png"
                    alt=""
                    height={600}
                    width={600}
                    quality={100}
                />
            </div>
            <div>
                <Image
                    src="/husko3.png"
                    alt=""
                    height={600}
                    width={600}
                    quality={100}
                />
            </div>
            <div>
                <Image
                    src="/husko4.png"
                    alt=""
                    height={600}
                    width={600}
                    quality={100}
                />
            </div>
            <div>
                <Image
                    src="/husko5.png"
                    alt=""
                    height={600}
                    width={600}
                    quality={100}
                />
            </div>
            <div>
                <Image
                    src="/husko6.png"
                    alt=""
                    height={600}
                    width={600}
                    quality={100}
                />
            </div>
        </div>
    );
}
